export const SET_WEB3_INSTANCE = 'SET_WEB3_INSTANCE';

export const SET_ACCOUNTS_INSTANCE = 'SET_ACCOUNTS_INSTANCE';

export const SET_CONTRACT_INSTANCE = 'SET_CONTRACT_INSTANCE';

export const STORE_CHARACTER_DATA = 'STORE_CHARACTER_DATA';

export const STORE_CHARACTER_SEARCH_RESULTS = 'STORE_CHARACTER_SEARCH_RESULTS';

export const SET_ACCOUNT_VOTED = 'SET_ACCOUNT_VOTED';

export const SET_TOP_CHARACTERS = 'SET_TOP_CHARACTERS';

export const SET_IS_LOADING = 'SET_IS_LOADING';